<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>ModernAtlas</AssemblyName>
    <RootNamespace>ModernAtlas</RootNamespace>
    <VintageStoryPath Condition="'$(VintageStoryPath)' == ''">/opt/vintagestory</VintageStoryPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VintageStoryPath)/VintagestoryAPI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VintagestoryLib">
      <HintPath>$(VintageStoryPath)/VintagestoryLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
